name: Build ARM 32-bit (armv7l)

on:
  workflow_dispatch:

jobs:
  build-armv7:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabi
          sudo apt-get install -y libc6-armel-cross libc6-dev-armel-cross
          sudo apt-get install -y libcrypt-dev:armhf || echo "libcrypt:armhf not found"
      
      - name: Compile for ARM 32-bit
        run: |
          arm-linux-gnueabi-gcc -Wall -O2 -mfpu=vfpv4 -mfloat-abi=hard -o man man.c -lpthread -lcrypt
          file man
      
      - name: Upload ARM binary
        uses: actions/upload-artifact@v4
        with:
          name: man
          path: man
